name: live
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  intl: ^0.16.1
  font_awesome_flutter: ^8.5.0
  carousel_slider: ^1.4.0
  cloud_firestore: ^0.13.0+1
  google_fonts: ^0.2.0
  dio: ^3.0.7
  rxdart: ^0.23.1
  bloc_pattern: ^2.5.1
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/