name: curriculo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  url_launcher: ^5.4.11
  font_awesome_flutter: ^8.8.1
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.2.6+1
  flutter:
    sdk: flutter


dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/language/

vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
    channel: flutter channel beta --force
scripts: 
    build: $channel & $clean & $get & $runner build --delete-conflicting-outputs
    watch: $channel & $clean & $get & $runner watch --delete-conflicting-outputs
