name: stelegram
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  font_awesome_flutter: ^8.8.1
  google_fonts: ^1.1.0
  cloud_firestore_web: ^0.1.1+2
  firebase_core_web: ^0.1.1+2
  cloud_firestore: ^0.13.7
  firebase_core: ^0.4.5
  firebase_database: ^3.1.6
  dio: ^3.0.9
  flutter_mobx: ^1.1.0+1
  mobx: ^1.2.1+1
  flutter_modular: ^1.3.1
  flutter:
    sdk: flutter



dev_dependencies:
  mockito: ^4.1.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.10.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    build: $clean & $get & $runner build --delete-conflicting-outputs
    watch: $clean & $get & $runner watch --delete-conflicting-outputs
