name: show_do_milhao
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  json_annotation: ^3.0.1
  flutter_modular: ^2.0.0+1
  mobx: ^1.2.1+2
  flutter_mobx: ^1.1.0+2
  dio: ^3.0.10
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  json_serializable: ^3.4.1
  mobx_codegen: ^1.1.0+1
  build_runner: ^1.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  
vars: 
    clean: flutter clean
    get: flutter pub get
    runner: flutter pub run build_runner
scripts: 
    build: $clean & $get & $runner build --delete-conflicting-outputs
    watch: $clean & $get & $runner watch --delete-conflicting-outputs

